### ISSUE TITLE
add an example for using releases instead of a repo

### ISSUE THREAD

**Issue by yankscally** [imjp94/gd-plug#35] opened 2024-08-20 16:11 UTC
using `plug("godot-jolt/godot-jolt")` doesn't work, as it is the GDExtension source code.

**Comment by yankscally** [comment] 2024-08-20 16:12
its in a zip here... any ideas?

https://github.com/godot-jolt/godot-jolt/releases/download/v0.13.0-stable/godot-jolt_v0.13.0-stable.zip

**Comment by imjp94** [comment] 2024-08-20 17:20
No, installing compiled binaries from github release is not supported, see #26 

Closing as duplicate of #26

**Closed by imjp94** 2024-08-20 17:20 UTC
